PREFIX rdef:   <http://github.com/wintechis/RDeF#>  
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
           
SELECT ?question  ?query 
WHERE {
    #_:placeholder will be replaced with the correct QueryScene URI before request is executed   
    _:placeholder   rdf:type        rdef:QueryScene ;
                    rdef:question       ?question   ;
                    rdef:markup_query   ?query   .
}