#chapter must not be specified, because chapters are organized as folders

PREFIX rdef:    <https://github.com/wintechis/RDeF#>
PREFIX dct:     <http://purl.org/dc/terms/>
PREFIX foaf:    <http://xmlns.com/foaf/spec/#>
PREFIX geo:     <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:    <https://www.w3.org/2000/01/rdf-schema#>
PREFIX schema:  <https://schema.org/>


SELECT ?episode  ?title  ?desc    ?location_name   ?link   ?lat    ?long   ?img 
WHERE {
    ?episode    rdf:type        rdef:Episode ;
                rdfs:label      ?title   ;
                dct:abstract    ?desc   ;
                schema:location _:b1    ;
                schema:attendee _:b3    .
    _:b1        rdfs:label      ?location_name   ;
                rdfs:seeAlso    ?link   ;
                geo:Point       _:b2    .
    _:b2        geo:lat         ?lat    ;
                geo:long        ?long   .
    _:b3        foaf:depiction  ?img    .      
}