PREFIX rdef:   <http://github.com/wintechis/RDeF#> 
PREFIX schema: <http://schema.org/> 
PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>   
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vgo:    <http://purl.org/net/VideoGameOntology#>  

SELECT ?title  ?desc  ?bg  ?fg  ?hl  ?cover_image  ?tags ?release
WHERE {
    _:b0    rdf:type        rdef:Story  ;
            dct:title       ?title      ;
            dct:abstract    ?desc       ;
            rdef:color_schema   _:b1    .

    _:b1    rdef:background_color   ?bg ;
            rdef:foreground_color   ?fg ;
            rdef:highlight_color    ?hl .

    OPTIONAL {
    _:b0 schema:image    ?cover_image   ;
         vgo:releaseDate ?release       ;       
         schema:keywords ?tags          .
        }
}